# Default initial positions for combined_robot's ros2_control fake system

initial_positions:
  arm1joint1: 0
  arm1joint2: 0
  arm1joint3: 0
  arm1joint4: 0
  arm1joint5: 0
  arm1joint6: 0
  arm1joint7: 0
  arm1joint8: 0
  arm2joint1: 0
  arm2joint2: 0
  arm2joint3: 0
  arm2joint4: 0
  arm2joint5: 0
  arm2joint6: 0
  arm2joint7: 0
  arm2joint8: 0